# Generated by Django 5.1.11 on 2025-09-03 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='url',
        ),
        migrations.AlterField(
            model_name='materials',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='materials',
            name='type',
            field=models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео')], max_length=10),
        ),
    ]
