# Generated by Django 5.2.1 on 2025-09-03 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_remove_materials_url_alter_materials_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'webp', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'mkv'])]),
        ),
    ]
