# Generated by Django 5.2.5 on 2025-08-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_name_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_name',
            name='created_at',
        ),
    ]
