# Generated by Django 5.2.1 on 2025-08-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_author_post_created_by_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_name',
            name='content',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
