# Generated by Django 5.2.1 on 2025-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_name_content_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic_name',
            name='content',
        ),
        migrations.AddField(
            model_name='topic_name',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
