# Generated by Django 5.2.5 on 2025-08-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='created_at',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='Вопрос', max_length=200),
            preserve_default=False,
        ),
    ]
