# Generated by Django 5.2.5 on 2025-08-15 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_text_choice_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default='Новый вопрос', max_length=255),
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
