# Generated by Django 5.2.5 on 2025-08-15 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_pub_date_poll_created_at_remove_poll_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
