# Generated by Django 5.2.5 on 2025-08-20 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_poll_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='question',
        ),
        migrations.AddField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='опрос', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll'),
        ),
    ]
