# Generated by Django 5.2.5 on 2025-08-31 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва проекту')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='portfolio/screenshots/', verbose_name='Скріншот')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/files/', verbose_name='Файл')),
                ('featured', models.BooleanField(default=False, verbose_name='Кращий проект')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
